from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import time
import traceback
from dataclasses import dataclass
from datetime import datetime
from hashlib import sha256
from pathlib import Path
from typing import Any, Callable


CONTRACT_VERSION = "patent_10_4_formal_close_min_contract_20260415"
FORMAL_SUBPROCESS_ENV = {"PYTHONDONTWRITEBYTECODE": "1"}
DEFAULT_TRACE_SHA256 = "c478b7cadeb1320362af0ea9921a1ad8592e2e53f8d90ebe800b3a25fd8ada3c"
DEFAULT_TRACE_SIZE_BYTES = 1118295183
DEFAULT_ARCHIVE_DATE = "20260426"
EXPECTED_B_CASE_IDS = (
    "depth_d0",
    "depth_d1",
    "depth_d2",
    "depth_d4",
    "depth_d8",
    "depth_d16",
    "event_c1",
    "event_c8",
    "event_c64",
    "event_c512",
    "event_c4096",
    "byte_s256",
    "byte_s4096",
    "byte_s65536",
    "byte_s1048576",
    "rho_r1_0",
    "rho_r2_0",
    "rho_r4_0",
    "rho_r8_0",
)
EXPECTED_C_SCENARIO_IDS = (
    "sidecar_mismatch",
    "cycle_inflation",
    "corrupt_segment",
    "io_guard",
)


@dataclass(frozen=True)
class WindowsFormalConfig:
    repo_root: Path
    archive_root: Path
    trace_path: Path
    expected_trace_sha256: str
    expected_trace_size_bytes: int
    scratch_dir: Path | None = None
    scenario_contract_path: Path | None = None
    scenario_contract: dict[str, Any] | None = None

    @property
    def prep_root(self) -> Path:
        return self.archive_root / "preparation"

    @property
    def a_root(self) -> Path:
        return self.archive_root / "A_control_plane_first"

    @property
    def b_root(self) -> Path:
        return self.archive_root / "B_budget_pre_freeze"

    @property
    def c_root(self) -> Path:
        return self.archive_root / "C_degraded_audit"


class Tee:
    def __init__(self, *streams: Any) -> None:
        self._streams = streams

    def write(self, data: str) -> int:
        for stream in self._streams:
            stream.write(data)
            stream.flush()
        return len(data)

    def flush(self) -> None:
        for stream in self._streams:
            stream.flush()


def detect_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def default_archive_root(repo_root: Path) -> Path:
    return repo_root / "docs" / f"evidence_proof_archive_{DEFAULT_ARCHIVE_DATE}" / "formal_10_4"


def default_source_report_path(repo_root: Path) -> Path:
    return repo_root / "docs" / "evidence_proof_archive_20260416" / "formal_10_4" / "preparation" / "frozen_input_source_report.json"


def add_common_arguments(
    parser: argparse.ArgumentParser,
    *,
    require_trace: bool = True,
    include_scratch_dir: bool = False,
) -> None:
    repo_root = detect_repo_root()
    parser.add_argument(
        "--archive-root",
        type=Path,
        default=default_archive_root(repo_root),
        help="Windows formal output root.",
    )
    parser.add_argument(
        "--trace",
        type=Path,
        required=require_trace,
        help="Windows-side qualified 1GB trace path.",
    )
    parser.add_argument(
        "--expected-trace-sha256",
        default=DEFAULT_TRACE_SHA256,
        help="Expected SHA-256 of the formal input trace.",
    )
    parser.add_argument(
        "--expected-trace-size-bytes",
        type=int,
        default=DEFAULT_TRACE_SIZE_BYTES,
        help="Expected size of the formal input trace.",
    )
    parser.add_argument(
        "--scenario-contract",
        type=Path,
        default=None,
        help="Scenario execution contract generated by runtime optimization formal matrix execute mode.",
    )
    if include_scratch_dir:
        parser.add_argument(
            "--scratch-dir",
            type=Path,
            default=Path(r"F:\rttrace\scratch"),
            help="Scratch directory used by Windows preflight.",
        )


def build_config(args: argparse.Namespace) -> WindowsFormalConfig:
    repo_root = detect_repo_root()
    trace_path = args.trace.expanduser().resolve()
    archive_root = args.archive_root.expanduser().resolve()
    scratch_dir = None
    if getattr(args, "scratch_dir", None) is not None:
        scratch_dir = args.scratch_dir.expanduser().resolve()
    scenario_contract_path = None
    scenario_contract = None
    raw_scenario_contract = getattr(args, "scenario_contract", None)
    if raw_scenario_contract is not None:
        scenario_contract_path = raw_scenario_contract.expanduser().resolve()
        if not scenario_contract_path.exists() or not scenario_contract_path.is_file():
            raise FileNotFoundError(f"scenario contract not found: {scenario_contract_path}")
        loaded = json_load(scenario_contract_path)
        if not isinstance(loaded, dict):
            raise ValueError(f"scenario contract must be a JSON object: {scenario_contract_path}")
        scenario_contract = dict(loaded)
    config = WindowsFormalConfig(
        repo_root=repo_root,
        archive_root=archive_root,
        trace_path=trace_path,
        expected_trace_sha256=str(args.expected_trace_sha256),
        expected_trace_size_bytes=int(args.expected_trace_size_bytes),
        scratch_dir=scratch_dir,
        scenario_contract_path=scenario_contract_path,
        scenario_contract=scenario_contract,
    )
    validate_scenario_contract_binding(config)
    return config


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def json_load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def json_write(path: Path, payload: Any) -> None:
    ensure_parent(path)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def _resolve_group_relative_path(path_text: Any, *, group_root: Path) -> Path | None:
    if path_text is None:
        return None
    text = str(path_text).strip()
    if not text:
        return None
    path = Path(text).expanduser()
    if not path.is_absolute():
        path = (group_root / path).resolve()
    return path


def _proof_digest_candidate_paths(package_root: Path) -> list[Path]:
    candidates = (
        package_root / "control" / "proof_digest.json",
        package_root / "packages" / "run_001" / "control" / "proof_digest.json",
        package_root / "package" / "control" / "proof_digest.json",
        package_root / "proof_digest.json",
    )
    unique: list[Path] = []
    seen: set[str] = set()
    for candidate in candidates:
        candidate_key = str(candidate)
        if candidate_key in seen:
            continue
        seen.add(candidate_key)
        unique.append(candidate)
    return unique


def _row_package_roots(row: dict[str, Any], *, group_root: Path) -> list[Path]:
    roots: list[Path] = []
    seen: set[str] = set()
    artifact_refs = row.get("artifact_refs")
    candidate_values = (
        row.get("package_path"),
        artifact_refs.get("package_path") if isinstance(artifact_refs, dict) else None,
    )
    for value in candidate_values:
        resolved = _resolve_group_relative_path(value, group_root=group_root)
        if resolved is None:
            continue
        resolved_key = str(resolved)
        if resolved_key in seen:
            continue
        seen.add(resolved_key)
        roots.append(resolved)
    scenario_id = str(row.get("scenario_id") or "").strip()
    if scenario_id:
        conventional_root = (group_root / "packages" / scenario_id).resolve()
        conventional_key = str(conventional_root)
        if conventional_key not in seen:
            roots.append(conventional_root)
    return roots


def load_group_proof_digest(
    row: dict[str, Any],
    *,
    group_root: Path,
    error_label: str,
) -> dict[str, Any]:
    inline = row.get("proof_digest")
    if isinstance(inline, dict) and inline:
        return dict(inline)
    attempted_paths: list[str] = []
    seen_paths: set[str] = set()
    for package_root in _row_package_roots(row, group_root=group_root):
        for digest_path in _proof_digest_candidate_paths(package_root):
            digest_key = str(digest_path)
            if digest_key in seen_paths:
                continue
            seen_paths.add(digest_key)
            attempted_paths.append(digest_key)
            if digest_path.exists() and digest_path.is_file():
                payload = json_load(digest_path)
                if isinstance(payload, dict) and payload:
                    return dict(payload)
                raise RuntimeError(f"{error_label} proof_digest payload is not a JSON object: {digest_path}")
    scenario_id = str(row.get("scenario_id") or "").strip() or "<unknown>"
    attempted_suffix = f"; attempted={attempted_paths}" if attempted_paths else ""
    raise RuntimeError(
        f"{error_label} does not contain proof_digest rows for scenario_id={scenario_id}{attempted_suffix}"
    )


def checksum_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def file_timestamp(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime).astimezone().isoformat()


def copy_file(src: Path, dst: Path) -> Path:
    ensure_parent(dst)
    shutil.copy2(src, dst)
    return dst


def copy_if_exists(src: Path, dst: Path) -> Path | None:
    if not src.exists():
        return None
    return copy_file(src, dst)


def copy_tree(src: Path, dst: Path) -> Path:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    return dst


def ensure_preparation_aliases(config: WindowsFormalConfig) -> dict[str, Path]:
    prep_root = config.prep_root
    prep_root.mkdir(parents=True, exist_ok=True)
    windows_env = prep_root / "windows_environment_summary.json"
    windows_input = prep_root / "input_qualification_report_windows.json"
    if not windows_env.exists():
        raise FileNotFoundError(f"missing Windows environment summary: {windows_env}")
    if not windows_input.exists():
        raise FileNotFoundError(f"missing Windows input qualification report: {windows_input}")
    compat_env = prep_root / "linux_environment_summary.json"
    compat_input = prep_root / "input_qualification_report.json"
    copy_file(windows_env, compat_env)
    copy_file(windows_input, compat_input)
    return {
        "windows_environment_summary": windows_env,
        "windows_input_qualification_report": windows_input,
        "compat_environment_summary": compat_env,
        "compat_input_qualification_report": compat_input,
    }


def runner_command(script_name: str, config: WindowsFormalConfig) -> str:
    archive_root = str(config.archive_root)
    trace_path = str(config.trace_path)
    return (
        f'python tool\\{script_name} '
        f'--archive-root "{archive_root}" '
        f'--trace "{trace_path}"'
    )


def checked_in_runner(group: str, repo_root: Path) -> Path:
    mapping = {
        "A": repo_root / "docs" / "evidence_proof_archive_20260418" / "formal_10_4" / "A_control_plane_first" / "run_formal_a_linux.py",
        "B": repo_root / "docs" / "evidence_proof_archive_20260418" / "formal_10_4" / "B_budget_pre_freeze" / "run_formal_b_linux.py",
        "C": repo_root / "docs" / "evidence_proof_archive_20260418" / "formal_10_4" / "C_degraded_audit" / "run_formal_c_linux.py",
    }
    return mapping[group]


def checked_in_summary_path(group: str, repo_root: Path) -> Path:
    mapping = {
        "A": repo_root / "docs" / "evidence_proof_archive_20260418" / "formal_10_4" / "A_control_plane_first" / "formal_summary_linux.json",
        "B": repo_root / "docs" / "evidence_proof_archive_20260418" / "formal_10_4" / "B_budget_pre_freeze" / "formal_summary_linux.json",
        "C": repo_root / "docs" / "evidence_proof_archive_20260418" / "formal_10_4" / "C_degraded_audit" / "formal_summary_linux.json",
    }
    return mapping[group]


def checked_in_summary(group: str, repo_root: Path) -> dict[str, Any]:
    return dict(json_load(checked_in_summary_path(group, repo_root)))


def load_module_from_path(module_path: Path, module_name: str, repo_root: Path) -> Any:
    repo_text = str(repo_root)
    if repo_text not in sys.path:
        sys.path.insert(0, repo_text)
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load module spec: {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def run_patched_main(
    *,
    module_path: Path,
    module_name: str,
    patcher: Callable[[Any], None],
    stdout_path: Path,
    stderr_path: Path,
    time_path: Path,
    repo_root: Path,
) -> None:
    module = load_module_from_path(module_path, module_name, repo_root)
    patcher(module)
    ensure_parent(stdout_path)
    ensure_parent(stderr_path)
    ensure_parent(time_path)
    started = time.perf_counter()
    old_stdout = sys.stdout
    old_stderr = sys.stderr
    exit_code = 0
    with stdout_path.open("w", encoding="utf-8") as stdout_handle, stderr_path.open(
        "w",
        encoding="utf-8",
    ) as stderr_handle:
        sys.stdout = Tee(old_stdout, stdout_handle)
        sys.stderr = Tee(old_stderr, stderr_handle)
        try:
            result = module.main()
            if isinstance(result, int):
                exit_code = result
        except SystemExit as exc:
            exit_code = int(exc.code) if isinstance(exc.code, int) else 1
            if exit_code:
                traceback.print_exc()
        except Exception:
            exit_code = 1
            traceback.print_exc()
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr
    elapsed = round(time.perf_counter() - started, 6)
    time_path.write_text(f"{elapsed:.6f}\n", encoding="utf-8")
    if exit_code:
        raise RuntimeError(f"runner failed: {module_path.name} exit_code={exit_code}")


def flatten_field_paths(payload: Any, prefix: str = "") -> set[str]:
    if isinstance(payload, dict):
        paths: set[str] = set()
        for key, value in payload.items():
            next_prefix = f"{prefix}.{key}" if prefix else str(key)
            paths.add(next_prefix)
            paths.update(flatten_field_paths(value, next_prefix))
        return paths
    if isinstance(payload, list):
        paths: set[str] = set()
        list_prefix = f"{prefix}[]" if prefix else "[]"
        paths.add(list_prefix)
        for item in payload:
            paths.update(flatten_field_paths(item, list_prefix))
        return paths
    return set()


def postprocess_summary(
    summary_path: Path,
    mutator: Callable[[dict[str, Any]], None],
    output_path: Path,
) -> Path:
    payload = dict(json_load(summary_path))
    mutator(payload)
    json_write(output_path, payload)
    return output_path


def run_subprocess(command: list[str], *, cwd: Path) -> None:
    env = os.environ.copy()
    env.update(FORMAL_SUBPROCESS_ENV)
    completed = subprocess.run(command, cwd=str(cwd), check=False, env=env)
    if completed.returncode != 0:
        raise RuntimeError(f"command failed with exit_code={completed.returncode}: {' '.join(command)}")


def artifact_record(role: str, path: Path) -> dict[str, Any]:
    exists = path.exists()
    record = {
        "role": role,
        "path": str(path),
        "exists": exists,
    }
    if exists and path.is_file():
        record.update(
            {
                "size_bytes": int(path.stat().st_size),
                "sha256": checksum_file(path),
                "last_write_time": file_timestamp(path),
            }
        )
    return record


OPTIONAL_PROOF_DIGEST_FIELD_SUFFIXES = frozenset(
    {
        "sidecar_bytes",
        "sidecar_bytes_scanned",
        "sidecar_index_build_seconds",
        "sidecar_selector_calls",
        "sidecar_selector_mode",
    }
)
OPTIONAL_FORMAL_PARITY_FIELD_PATHS = frozenset(
    {
        "artifact_refs.scenario_execution_contract",
    }
)
OPTIONAL_FORMAL_PARITY_FIELD_PREFIXES = (
    "scenario_execution",
)


def is_optional_formal_parity_field_path(path: str) -> bool:
    path_text = str(path or "")
    if path_text in OPTIONAL_FORMAL_PARITY_FIELD_PATHS:
        return True
    if any(path_text == prefix or path_text.startswith(f"{prefix}.") for prefix in OPTIONAL_FORMAL_PARITY_FIELD_PREFIXES):
        return True
    tokens = path_text.split(".")
    if not tokens:
        return False
    proof_tokens = {"proof_digest", "proof_digest[]"}
    return bool(set(tokens).intersection(proof_tokens)) and tokens[-1] in OPTIONAL_PROOF_DIGEST_FIELD_SUFFIXES


def formal_parity_field_paths(payload: Any) -> set[str]:
    return {path for path in flatten_field_paths(payload) if not is_optional_formal_parity_field_path(path)}


def jsonl_write(path: Path, rows: list[Any]) -> None:
    ensure_parent(path)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False))
            handle.write("\n")


def scenario_contract_payload(config: WindowsFormalConfig) -> dict[str, Any]:
    return dict(config.scenario_contract or {})


def scenario_definition(config: WindowsFormalConfig) -> dict[str, Any]:
    return dict(scenario_contract_payload(config).get("scenario") or {})


def _first_nonempty_string(*values: Any) -> str | None:
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return None


def _first_present_value(*values: Any) -> Any:
    for value in values:
        if value is not None:
            return value
    return None


def scenario_scheduler_strategy(config: WindowsFormalConfig) -> str | None:
    payload = scenario_contract_payload(config)
    input_contract = dict(payload.get("input_contract") or {})
    return _first_nonempty_string(
        payload.get("scheduler_strategy"),
        input_contract.get("scheduler_strategy"),
    )


def scenario_source_report_path(config: WindowsFormalConfig) -> Path | None:
    payload = scenario_contract_payload(config)
    input_contract = dict(payload.get("input_contract") or {})
    value = _first_nonempty_string(
        payload.get("source_report_path"),
        input_contract.get("source_report_path"),
    )
    if value is None:
        return None
    return Path(value).expanduser().resolve()


def validate_scenario_contract_binding(
    config: WindowsFormalConfig,
    *,
    source_report_path: Path | None = None,
) -> None:
    if config.scenario_contract_path is None:
        return
    payload = scenario_contract_payload(config)
    input_contract = dict(payload.get("input_contract") or {})
    scenario_value = scenario_id(config)
    if scenario_value is None:
        raise ValueError(
            f"scenario contract missing scenario.scenario_id: {config.scenario_contract_path}"
        )
    trace_path_value = _first_nonempty_string(
        dict(payload.get("trace") or {}).get("path"),
        input_contract.get("trace_path"),
    )
    if trace_path_value is None:
        raise ValueError(
            f"scenario contract missing trace path binding: {config.scenario_contract_path}"
        )
    contract_trace_path = Path(trace_path_value).expanduser().resolve()
    if contract_trace_path != config.trace_path.resolve():
        raise ValueError(
            "scenario contract trace path mismatch: "
            f"contract={contract_trace_path} cli={config.trace_path.resolve()}"
        )
    trace_sha256 = _first_nonempty_string(
        dict(payload.get("trace") or {}).get("sha256"),
        input_contract.get("trace_sha256"),
    )
    if trace_sha256 is None:
        raise ValueError(
            f"scenario contract missing trace sha256 binding: {config.scenario_contract_path}"
        )
    if trace_sha256 != config.expected_trace_sha256:
        raise ValueError(
            "scenario contract trace sha256 mismatch: "
            f"contract={trace_sha256} cli={config.expected_trace_sha256}"
        )
    trace_size_raw = _first_present_value(
        dict(payload.get("trace") or {}).get("size_bytes"),
        input_contract.get("trace_size_bytes"),
    )
    if trace_size_raw is None:
        raise ValueError(
            f"scenario contract missing trace size binding: {config.scenario_contract_path}"
        )
    try:
        trace_size_bytes = int(trace_size_raw)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"scenario contract trace size must be an integer: {config.scenario_contract_path}"
        ) from exc
    if trace_size_bytes != config.expected_trace_size_bytes:
        raise ValueError(
            "scenario contract trace size mismatch: "
            f"contract={trace_size_bytes} cli={config.expected_trace_size_bytes}"
        )
    scheduler_strategy = scenario_scheduler_strategy(config)
    if scheduler_strategy is None:
        raise ValueError(
            f"scenario contract missing scheduler_strategy: {config.scenario_contract_path}"
        )
    if source_report_path is not None:
        contract_source_report_path = scenario_source_report_path(config)
        if contract_source_report_path is None:
            raise ValueError(
                f"scenario contract missing source_report_path binding: {config.scenario_contract_path}"
            )
        if contract_source_report_path != source_report_path.expanduser().resolve():
            raise ValueError(
                "scenario contract source report mismatch: "
                f"contract={contract_source_report_path} "
                f"cli={source_report_path.expanduser().resolve()}"
            )


def scenario_id(config: WindowsFormalConfig) -> str | None:
    value = scenario_definition(config).get("scenario_id")
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def scenario_advisor_config(config: WindowsFormalConfig) -> tuple[bool, str, dict[str, Any]]:
    scenario = scenario_definition(config)
    advisor_enabled = bool(scenario.get("advisor_enabled"))
    advisor_mode = str(scenario.get("advisor_mode") or ("disabled" if not advisor_enabled else "heuristic")).strip()
    advisor_config: dict[str, Any] = {"advisor_mode": advisor_mode}
    optional_dependency = str(scenario.get("optional_dependency") or "").strip()
    if advisor_mode == "openai_structured":
        advisor_config["llm_enabled"] = True
    elif advisor_mode == "offline_coefficients":
        if optional_dependency:
            advisor_config["optional_dependency"] = optional_dependency
        repo_candidate = config.repo_root / "tmp" / "runtime_optimization_formal_matrix" / "advisor_optional_sklearn_coefficients.json"
        archive_candidate = config.archive_root / "control" / "advisor_optional_sklearn_coefficients.json"
        coefficients_path = archive_candidate if archive_candidate.exists() else repo_candidate
        if not coefficients_path.exists():
            _write_default_offline_coefficients(coefficients_path)
        if coefficients_path.exists():
            advisor_config["coefficients_path"] = str(coefficients_path.resolve())
    return advisor_enabled, advisor_mode, advisor_config


def scenario_ticket_fast_path_enabled(config: WindowsFormalConfig) -> bool:
    return bool(scenario_definition(config).get("ticket_fast_path_enabled"))


def scenario_streaming_write_enabled(config: WindowsFormalConfig) -> bool:
    return bool(scenario_definition(config).get("streaming_write_enabled"))


def scenario_run_id(config: WindowsFormalConfig, *, default: str) -> str:
    payload = scenario_contract_payload(config)
    scenario = scenario_definition(config)
    return (
        str(payload.get("run_id") or scenario.get("scenario_id") or default).strip()
        or default
    )


def scenario_experiment_params(config: WindowsFormalConfig, *, proof_group: str) -> dict[str, Any]:
    payload = scenario_contract_payload(config)
    scenario = scenario_definition(config)
    experiment_params = {
        "proof_group": proof_group,
        "scenario_id": str(scenario.get("scenario_id") or "").strip() or None,
        "formal_matrix_mode": str(payload.get("formal_matrix_mode") or "execute"),
        "scheduler_strategy": scenario_scheduler_strategy(config),
    }
    if config.scenario_contract_path is not None:
        experiment_params["scenario_contract_path"] = str(config.scenario_contract_path.resolve())
    return {key: value for key, value in experiment_params.items() if value is not None}


def scenario_contract_artifact_record(config: WindowsFormalConfig) -> dict[str, Any] | None:
    if config.scenario_contract_path is None:
        return None
    return artifact_record("scenario_execution_contract", config.scenario_contract_path)


def _write_default_offline_coefficients(path: Path) -> None:
    from parser.runtime_advisor import coefficient_payload_checksum

    payload = {
        "status": "trained",
        "model_ref": "offline-coefficients-sklearn-v1",
        "optional_dependency": "sklearn",
        "training_rows": 2,
        "feature_names": [
            "input_bytes",
            "sidecar_bytes",
            "sidecar_row_count",
            "sidecar_bytes_scanned",
            "sidecar_validate_seconds",
            "index_build_open_seconds",
            "package_write_seconds",
            "peak_rss_mb",
        ],
        "runtime_intercept": 1.0,
        "runtime_weights": {
            "input_bytes": 0.0,
            "sidecar_bytes": 0.0,
            "sidecar_row_count": 0.0,
            "sidecar_bytes_scanned": 0.0,
            "sidecar_validate_seconds": 0.0,
            "index_build_open_seconds": 0.0,
            "package_write_seconds": 0.0,
            "peak_rss_mb": 0.0,
        },
        "backtest": {
            "mean_absolute_error": 0.0,
            "r2_score": 1.0,
        },
    }
    payload["model_checksum"] = coefficient_payload_checksum(payload)
    json_write(path, payload)
