"""Public spec helpers and legacy compatibility exports.

Canonical runtime models live in ``parser.models``. Model names re-exported
from this package remain available for compatibility, but callers should treat
``spec.models`` as a compatibility surface rather than the primary runtime
model definition site.
"""

from .io import (
    ASSET_ROOT,
    SCHEMA_ROOT,
    checksum_file,
    checksum_text,
    json_dump,
    jsonl_iter,
    json_load,
    jsonl_dump,
    jsonl_load,
    load_default_dictionary,
    load_schema,
    serialize,
)
from .models import (
    Alert,
    AnalysisContext,
    Bookmark,
    CANONICAL_PEER_MODEL_NAMES,
    CANONICAL_RUNTIME_MODEL_MODULE,
    CompareScope,
    Diagnosis,
    DiffBundle,
    DiffDetail,
    DiffSummary,
    EventCursor,
    EventPage,
    EvidenceRef,
    ExecSlice,
    GlobalHeader,
    IndexBundle,
    IrqSpan,
    LEGACY_MODEL_DEPRECATION_NOTES,
    LEGACY_MODEL_OWNER_MAP,
    LEGACY_ONLY_MODEL_NAMES,
    MetricResult,
    PlaybackState,
    RebuildBundle,
    RETIRED_LEGACY_MODEL_NAMES,
    ResourceGraph,
    TaskStateQuery,
    TaskStateSeg,
    TaskStateViewModel,
    UnifiedEvent,
    UntrustedWindow,
    canonical_model,
    has_canonical_peer,
    is_legacy_only_model,
)
from .result import Result

__all__ = [
    "ASSET_ROOT",
    "SCHEMA_ROOT",
    "Alert",
    "AnalysisContext",
    "Bookmark",
    "CANONICAL_PEER_MODEL_NAMES",
    "CANONICAL_RUNTIME_MODEL_MODULE",
    "CompareScope",
    "Diagnosis",
    "DiffBundle",
    "DiffDetail",
    "DiffSummary",
    "EventCursor",
    "EventPage",
    "EvidenceRef",
    "ExecSlice",
    "GlobalHeader",
    "IndexBundle",
    "IrqSpan",
    "LEGACY_MODEL_DEPRECATION_NOTES",
    "LEGACY_MODEL_OWNER_MAP",
    "LEGACY_ONLY_MODEL_NAMES",
    "MetricResult",
    "PlaybackState",
    "RebuildBundle",
    "RETIRED_LEGACY_MODEL_NAMES",
    "ResourceGraph",
    "Result",
    "TaskStateQuery",
    "TaskStateSeg",
    "TaskStateViewModel",
    "UnifiedEvent",
    "UntrustedWindow",
    "canonical_model",
    "checksum_file",
    "checksum_text",
    "has_canonical_peer",
    "is_legacy_only_model",
    "json_dump",
    "jsonl_iter",
    "json_load",
    "jsonl_dump",
    "jsonl_load",
    "load_default_dictionary",
    "load_schema",
    "serialize",
]
